### ISSUE TITLE
freePort() false negative?

### ISSUE THREAD

**Issue by wlandau** [HenrikBengtsson/parallelly#101]
I am testing a known situation where a port should be occupied. Using [`mirai`](https://github.com/shikokuchuo/mirai) 0.7.2.9013, I run client and server processes which runs a TCP socket through port 5000.

```r
# client
mirai::daemons("tcp://192.168.0.2:5000")

# server
mirai::server("tcp://192.168.0.2:5000")
```

Then in a different R session, I run a `pprof` server on that same port.

```r
proffer::pprof(Sys.sleep(1), host = "0.0.0.0", port = "5000")
```

When I navigate a browser to <http://127.0.0.1:5000/ui/flamegraph>, I get an HTTP 403 error. But when I run `parallelly::freePort(ports = 5000)`, I get `5000`, which I understand to mean that the function is claiming the port is free.

The motivation is https://github.com/shikokuchuo/mirai/discussions/31, where I am trying to figure out a way to use the [`mirai` local active queue](https://github.com/shikokuchuo/mirai#connecting-to-remote-servers-through-a-local-server-queue) in a way that will not consume too many ports on shared systems.

**Comment by HenrikBengtsson** [comment]
> But when I run `parallelly::freePort(ports = 5000)`, I get 5000, which I understand to mean that the function is claiming the port is free.

This is because the default is `default = "random"`, which will return a random port in `ports` as a last attempt without verifying it actually exists.  It's a bit of an odd default, but I think I picked it as a fallback that is backward compatibility with how `parallel::makeCluster()` works (=a random port without checking it's available).

If you use `default = NA_integer_` you should get that as the result, i.e. try `parallelly::freePort(ports = 5000, default = NA_integer_)`.

It's probably more sensible to have `default = NA_integer_` as the default; I'll think about it.

**Comment by HenrikBengtsson** [comment]
Actually, the main reason for `default = "random"` being the default is: "If port querying is not supported, as in R (< 4.0.0), then `default` is returned."  In other words, in order to avoid having to do things like `port = if (getRversion() >= "4.0.0") parallelly::freePort(ports) else sample(ports, size = 1L)` we can just write `port = parallelly::freePort(ports)`.  It's the best we can do with base-R.

But, maybe I can make the new default `default = if (getRversion() >= "4.0.0") NA_character_ else "random"` - that might be a tad more sensible.

**Comment by HenrikBengtsson** [comment]
Develop version now use `default = if (getRversion() >= "4.0.0") NA_character_ else "random"` as the default.

@wlandau, can you please retry and see if it now works as you first expected?

**Comment by wlandau** [comment]
For some reason my original test case is having trouble simulating an occupied port, but I do now notice freePort(51925) returns 51925 and freePort(22) returns NA. In the CRAN version (1.34.0), freePort(22) return 22. So I think the issue is fixed. Thanks!

**Comment by HenrikBengtsson** [comment]
parallelly 1.35.0 implementing this was just accepted on CRAN.
