### ISSUE TITLE
plan(multisession) leaks connections

### ISSUE THREAD

**Issue by tzakharko** [HenrikBengtsson/parallelly#56]
**Describe the bug**

Using `plan(multisession)` generates warnings about unused connections. This is so at least on macOS with R 4.1.0. I did not have the chance to test other platforms. 

**Reproduce example**

```r
future::plan(future::multisession)
gc()
# In .Internal(gc(verbose, reset, full)) :
#  closing unused connection 3 (localhost)
```

**Session information**

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0    parallelly_1.26.1 tools_4.1.0       parallel_4.1.0   
[5] listenv_0.8.0     codetools_0.2-18  digest_0.6.27     globals_0.14.0   
[9] future_1.21.0    
```

**Comment by HenrikBengtsson** [comment]
Fixed in the develop version of **parallelly**, cf. commit 67836def.  To install that version, use:

```r
remotes::install_github("HenrikBengtsson/parallelly", ref="develop")
```


Details: The problem was that the socket connection was indeed set up to be cleaned up automatically when exiting `makeClusterPSOCK()`;

https://github.com/HenrikBengtsson/parallelly/blob/67836defe0bee750d9629803e9b40fc55371a839/R/makeClusterPSOCK.R#L200

However, an older strategy would override this at the very end:

https://github.com/HenrikBengtsson/parallelly/blob/67836defe0bee750d9629803e9b40fc55371a839/R/makeClusterPSOCK.R#L350-L351

**Comment by tzakharko** [comment]
Thanks for the quick fix! Can confirm that the warning is gone. As far as I am concerned, this issue can be closed.
